### ISSUE TITLE
Read after close gives this

### ISSUE THREAD

**Issue by indutny** [random-access-storage/random-access-file#11]
```
Trace
    at Class.destroy (/Users/findutnyy/Code/indutny/hyperfeed/node_modules/from2/index.js:76:15)
    at check (/Users/findutnyy/Code/indutny/hyperfeed/node_modules/from2/index.js:57:28)
    at /Users/findutnyy/Code/indutny/hyperfeed/node_modules/hypercore/index.js:974:21
    at onread (/Users/findutnyy/Code/indutny/hyperfeed/node_modules/random-access-file/index.js:101:14)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:628:17)
events.js:163
      throw er; // Unhandled 'error' event
```

**Comment by indutny** [comment]
This is probably not a bug of this repo as it is, but is rather a bug of hypercore.

**Comment by indutny** [comment]
Got this while attempting to close loading hypercore.
